export const Actiontypes = {
  SET_USER: "SET_USER",
  FETCH_MEAL: "FETCH_MEAL",
  REMOVE_MEAL: "REMOVE_MEAL",
  DAY_MEAL: "DAY_MEAL",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  UNSET_CURRENT_USER: "UNSET_CURRENT_USER",
  SET_ALLEREGY: "SET_ALLEREGY",
  DELETE_MEAL: "DELETE_MEAL",
  RESET_MEAL: "RESET_MEAL",
};
